version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_petshop
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
